language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required

before_install:
  - pip install --upgrade pytest

install:
  - python setup.py install
  - pip install -r dev-requirements.txt

script: py.test -vvv ./tests
